site_name: wai-annotations manual
site_url: https://ufdl.cms.waikato.ac.nz/wai-annotations-manual
site_description: Manual for the wai-annotations library for converting various annotation formats into each other
theme:
    name: readthedocs
markdown_extensions:
    - toc:
        baselevel: 3
nav:
  - 'Home': index.md
  - 'Installation': install.md
  - 'Usage': usage.md
  - 'Examples': examples.md
  - 'Plugin guide': plugin.md
  - 'Domains': domains.md
  - 'Plugins': plugins.md
  - 'Glossary': glossary.md

