site_name: wai-annotations manual
site_url: https://ufdl.cms.waikato.ac.nz/wai-annotations-manual
site_description: Manual for the wai-annotations library for converting various annotation formats into each other
theme:
    name: material
markdown_extensions:
    - toc:
        baselevel: 2
        permalink: "#"
    - attr_list
plugins:
    # https://github.com/soulless-viewer/mkdocs-video
    - mkdocs-video
    - search
nav:
  - 'Home': index.md
  - 'Installation': install.md
  - 'Usage': usage.md
  - 'Examples':
    - 'Overview': examples_overview.md
    - 'Format conversions': examples_formats.md
    - 'Audio processing': examples_audio.md
    - 'Image dataset augmentation': examples_imgaug.md
    - 'Image dataset statistics': examples_imgstats.md
    - 'Image dataset visualizations': examples_imgvis.md
    - 'Video handling': examples_video.md
    - 'Predictions via Redis': examples_redis_predictions.md
    - 'Generic plugin wrappers': examples_generic.md
  - 'Docker': docker.md
  - 'Architecture overview': architecture_overview.md
  - 'Plugin guide': plugin.md
  - 'Domains': domains.md
  - 'Plugins': plugins.md
  - 'Glossary': glossary.md

